name: Prepare release

on:
  push:
    tags: [ 'v*.*.*']
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Set up dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel setuptools_scm build twine
          python -m pip install -e .
        shell: bash
      - name: Build wheel
        run: python -m build
      - name: Verify build
        run: twine check dist/*
